- hosts: all
  remote_user: root

  tasks:
    - name: copy mysql57.tar
      copy: src=/root/mysql57.tar dest=/root
    - name: load mysql57
      shell: chdir=/root docker load < mysql57.tar

    - name: copy tomcat.tar
      copy: src=/root/tomcat.tar dest=/root
    - name: load tomcat
      shell: chdir=/root docker load < tomcat.tar
