version: '3.6'
services:
  mysql57:
    image: mysql:5.7
    volumes:
      - /mysql57:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  tomcat:
    image: tomcat:v2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "82:8080"
    environment:  
      - MYSQL_SERVICE_HOST=mole_mysql57
      - MYSQL_SERVICE_PORT=3306
